### PR TITLE
Added default value column

### PR DESCRIPTION
**Pull request by rokde**
env($key[, $default]); -> adds default values found in source to the result table

```
$ php artisan env:gen
preparing files
searching files
 5652/5652 [============================] 100%
saving all variables that we found to the .env.gen file
+----------------+---------+-----------+--------------------+
| Name           | On .env | On source | Default            |
+----------------+---------+-----------+--------------------+
| #DB_HOST       | Yes     | No        |                    |
| #DB_SOCKET     | Yes     | No        |                    |
| APP_DEBUG      | Yes     | Yes       | false              |
| APP_ENV        | Yes     | Yes       | 'production'       |
| APP_KEY        | Yes     | No        |                    |
| CACHE_DRIVER   | Yes     | Yes       | 'file'             |
| DB_DATABASE    | Yes     | Yes       | 'forge'            |
| DB_HOST        | Yes     | Yes       | 'localhost'        |
| DB_PASSWORD    | Yes     | Yes       | ''                 |
| DB_SOCKET      | No      | Yes       | ''                 |
| DB_USERNAME    | Yes     | Yes       | 'forge'            |
| MAIL_HOST      | Yes     | Yes       | 'smtp.mailgun.org' |
| MAIL_PASSWORD  | Yes     | No        |                    |
| MAIL_PORT      | Yes     | No        |                    |
| MAIL_USERNAME  | Yes     | No        |                    |
| QUEUE_DRIVER   | No      | Yes       | 'sync'             |
| SESSION_DRIVER | Yes     | Yes       | 'file'             |
+----------------+---------+-----------+--------------------+
done
```

### CODE REVIEW

**Comment by mathiasgrimm** [comment]
Well done

**Comment by mathiasgrimm** [comment]
What if there are 2 different values for the same variable?

Something like env('MY_VAR', 1); and in other part of the code there is something like env('MY_VAR', 2); ?

**Comment by rokde** [comment]
Good question. Maybe we can fetch default values as array and implode the results in the table.

**Comment by mathiasgrimm** [comment]
Done on https://github.com/mathiasgrimm/laravel-dot-env-gen/pull/6 however still missing the part that split different default values

**Pull request closed without merging**
