### PR TITLE
Add support for directory exclusion rules (Resolves #12)

### LINKED ISSUE #12: ignore folder/pattern
add a way to ignore folders like vendor and any other folder in order to reduce the scanning time

### PR DESCRIPTION
**Pull request by codyphobe**
Adds publishable config file to declare exclusion rules. It may not be the prettiest solution, but it works.

### CODE REVIEW

**Comment by codyphobe** [comment]
As for the default behavior, a new install of L5 only contains one reference to `APP_ENV` and that is inside `vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/DetectEnvironment.php`. Rather than exclude it and produce an unused warning for `APP_ENV`, I opted to include the extra ~460 files.

**Comment by mathiasgrimm** [comment]
Does it work if one does not create the config file?

It should work and assume that there is no folders to be ignored, just to make it backwards compatible.

**Comment by codyphobe** [comment]
Yes, if the config file is not published then it will use the one in `src/config`.

When you say it should assume there are no folders to be ignored, do you mean to scan all files by default?

**Comment by mathiasgrimm** [comment]
Well... in our case is just the laravel folder that has some env variable, but for someone might be different and be already relying on this tool. We should keep it 100% back compatible. I think keeping 100% compatible is always a good option and the speed is not a huge problem in our case. So if someone wants to disable, disable then.

We should be able to somehow add this recommendation.
I think we could add a message to the env:gen output recommending or at least suggesting that is possible to change the default behaviour 

What do you think?

**Comment by mathiasgrimm** [comment]
another thing, i think we should be able to specify the root folder that will be scanned so that we can unit test as well, but this could be a different a different PR for later on.

**Comment by codyphobe** [comment]
If there are no rules, which is now the default setting, it will inform the user that they can speed up the scanning process.

As for specifying the root, that could be done with a simple option flag defaulting to `base_path()`.

**Comment by mathiasgrimm** [comment]
Grand!

**Comment by mathiasgrimm** [comment]
I think the message could always appear

**Comment by mathiasgrimm** [comment]
Done!

Thanks once again!

**Pull request merged**
